In [5]:
import pandas as pd
import numpy as np
from scipy.stats import norm

In [6]:
df = pd.read_excel (r'C:\Users\aahr1\Documents\Jupyter Notebook\NaiveBayes\dataSet.xlsx')

In [7]:
features=df.iloc[:,:len(df.columns)-1]
lables=df.loc[:,'label'].eq(1)

In [8]:
ms=np.empty([len(features.columns),4])

In [9]:
for i in range(len(features.columns)):    
            
    a=features.iloc[np.where(lables==False)].iloc[:,i]
    b=features.iloc[np.where(lables==True)].iloc[:,i]
    
    mu0=np.mean(a)
    std0=np.std(a)
    
    mu1=np.mean(b)
    std1=np.std(b)
    
    ms[i,:]=[mu0,std0,mu1,std1]

In [11]:
print(ms)
test=[100  ,  16.22, 17.25]

[[ 94.66666667   3.68178701 109.5          6.23832242]
 [ 14.33333333   0.81952561  16.27833333   0.64092165]
 [ 13.91666667   1.12422813  17.12166667   0.74599859]]


In [33]:
norm0,norm1=1,1

In [34]:
for i in range(len(ms)):
    norm0*=norm.pdf(test[i], loc=ms[i,0], scale=ms[i,1])
    norm1*=norm.pdf(test[i], loc=ms[i,2], scale=ms[i,3])

In [35]:
p0=np.sum(df.loc[:,'label']==0)/len(df)
p1=np.sum(df.loc[:,'label']==1)/len(df)

In [36]:
if norm0*p0 > norm1*p1:
    print('az class 0')
else:
    print('az class 1')

az class 1
